
INSERT IGNORE INTO `#__cck_core_types` (`id`, `asset_id`, `title`, `name`, `alias`, `folder`, `template_admin`, `template_site`, `template_content`, `template_intro`, `description`, `indexed`, `published`, `options_admin`, `options_site`, `options_content`, `options_intro`, `admin_form`, `location`, `locked`, `parent`, `parent_inherit`, `permissions`, `storage_location`, `stylesheets`, `version`, `checked_out`, `checked_out_time`, `access`, `created_date`, `created_user_id`, `modified_date`, `modified_user_id`) VALUES
(55, 0, '[Article] Grp (Content) Meta', 'article_grp_content_meta', '', 10, 0, 0, 0, 0, '', 'none', 1, '', '', '', '', 0, 'collection', 1, '', 0, '', 'joomla_article', '', 6, 0, '0000-00-00 00:00:00', 3, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
(56, 0, '[Article] Grp (Content) Snippet', 'article_grp_content_snippet', '', 10, 0, 0, 0, 0, '', 'none', 1, '', '', '', '', 0, 'collection', 1, '', 0, '', 'joomla_article', '', 4, 0, '0000-00-00 00:00:00', 3, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
(57, 0, '[Article] Grp (Content) Text', 'article_grp_content_text', '', 10, 0, 0, 0, 0, '', 'none', 1, '', '', '', '', 0, 'collection', 1, '', 0, '', 'joomla_article', '', 5, 0, '0000-00-00 00:00:00', 3, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
(58, 0, '[Article] Grp (Content) Archived', 'article_grp_content_archived', '', 10, 0, 0, 0, 0, '', 'none', 1, '', '', '', '', 0, 'collection', 1, '', 0, '', 'joomla_article', '', 4, 0, '0000-00-00 00:00:00', 3, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0),
(59, 0, 'Menu', 'menu', '', 54, 0, 0, 0, 0, '', 'none', 1, '', '', '', '', 0, '', 1, '', 0, '', 'joomla_menu', '', 1, 0, '0000-00-00 00:00:00', 3, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0);

INSERT IGNORE INTO `#__cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_cck`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES
(861, 'Core Parent (Site)', 'core_parent_site', 3, 'select_dynamic', '', 0, 'Parent', 'None', 3, '', '', '', '', '{\"query\":\"\",\"table\":\"#__cck_core_sites\",\"name\":\"title\",\"where\":\"id != $uri->getInt(\'id\') AND published != -44\",\"value\":\"id\",\"orderby\":\"title\",\"orderby_direction\":\"ASC\",\"limit\":\"\",\"language_detection\":\"joomla\",\"language_codes\":\"EN,GB,US,FR\",\"language_default\":\"EN\",\"attr1\":\"\",\"attr2\":\"\",\"attr3\":\"\",\"attr4\":\"\",\"attr5\":\"\",\"attr6\":\"\"}', 0, 255, 32, 0, 0, 0, 0, ',', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', '', 'parent_id', '', '', '', 0, '0000-00-00 00:00:00'),
(871, 'Redirection (Archived Item)', 'redirection_archived_item', 3, 'message_redirection', '', 1, '', '', 3, '', '', '', '', '{\"itemid\":\"-1\",\"timeout\":\"0\",\"timeout_ms\":\"\",\"message_style\":\"warning\",\"message\":\"The page you were looking for does not exist anymore\"}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'none', '', '', '', 'redirection_archived_item', '', '', '', 0, '0000-00-00 00:00:00'),
(872, 'Message (Archived Item)', 'message_archived_item', 3, 'message_redirection', '', 1, '', '', 3, '', '', '', '', '{\"itemid\":\"\",\"timeout\":\"0\",\"timeout_ms\":\"\",\"message_style\":\"warning\",\"message\":\"This page has been archived and the content may be missing or not accurate\"}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'none', '', '', '', 'message_archived_item', '', '', '', 0, '0000-00-00 00:00:00'),
(873, 'Break (Archived Item)', 'break_archived_item', 3, 'cck_break', '', 1, '', '', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'none', '', '', '', 'break_archived_item', '', '', '', 0, '0000-00-00 00:00:00'),
(874, 'Article Archived Mode', 'art_archived_mode', 22, 'select_simple', '', 1, 'Status Archived Mode', ' ', 3, '', '', '0', 'An additional message is displayed=0||Only a message is visible=1||The page is redirected=2', '{\"options\":[]}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'standard', '', 'joomla_article', '#__cck_store_item_content', 'archived_mode', '', '', '', 0, '0000-00-00 00:00:00'),
(875, '[Article] Grp (Content) Archived', 'art_grp_content_archived', 22, 'group', '', 1, 'clear', '', 3, '', '', '', '', '', 0, 255, 32, 0, 1, 0, 0, '', 0, '', 'article_grp_content_archived', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'none', '', '', '', 'art_grp_content_archived', '', '', '', 0, '0000-00-00 00:00:00');

INSERT IGNORE INTO `#__cck_core_type_field` (`typeid`, `fieldid`, `client`, `ordering`, `label`, `variation`, `variation_override`, `required`, `required_alert`, `validation`, `validation_options`, `link`, `link_options`, `live`, `live_options`, `live_value`, `markup`, `markup_class`, `typo`, `typo_label`, `typo_options`, `stage`, `access`, `restriction`, `restriction_options`, `computation`, `computation_options`, `conditional`, `conditional_options`, `position`) VALUES
(58, 301, 'content', 2, 'clear', '', '', '', '', '', '', '', '', '', '', '', 'clear', '', '', 0, '', 0, 1, '', '', '', '', '', '', '_main_'),
(58, 871, 'content', 4, 'clear', '', '', '', '', '', '', '', '', '', '', '', 'clear', '', '', 0, '', 0, 1, 'x', '{\"conditions\":[{\"trigger\":\"cck_fields\",\"options\":{\"property\":\"value\",\"property_custom\":\"\",\"do\":\"0\",\"trigger\":\"art_state\",\"match\":\"isEqual\",\"values\":\"2\",\"live\":\"\"}},{\"trigger\":\"cck_fields\",\"options\":{\"property\":\"value\",\"property_custom\":\"\",\"do\":\"0\",\"trigger\":\"art_archived_mode\",\"match\":\"isEqual\",\"values\":\"2\",\"live\":\"\"}}]}', '', '', '', '', '_main_'),
(58, 872, 'content', 3, 'clear', '', '', '', '', '', '', '', '', '', '', '', 'clear', '', '', 0, '', 0, 1, 'x', '{\"conditions\":[{\"trigger\":\"cck_fields\",\"options\":{\"property\":\"value\",\"property_custom\":\"\",\"do\":\"0\",\"trigger\":\"art_state\",\"match\":\"isEqual\",\"values\":\"2\",\"live\":\"\"}},{\"trigger\":\"cck_fields\",\"options\":{\"property\":\"value\",\"property_custom\":\"\",\"do\":\"1\",\"trigger\":\"art_archived_mode\",\"match\":\"isEqual\",\"values\":\"2\",\"live\":\"\"}}]}', '', '', '', '', '_main_'),
(58, 873, 'content', 5, 'clear', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, '', 0, 1, 'x', '{\"conditions\":[{\"trigger\":\"cck_fields\",\"options\":{\"property\":\"value\",\"property_custom\":\"\",\"do\":\"0\",\"trigger\":\"art_state\",\"match\":\"isEqual\",\"values\":\"2\",\"live\":\"\"}},{\"trigger\":\"cck_fields\",\"options\":{\"property\":\"value\",\"property_custom\":\"\",\"do\":\"0\",\"trigger\":\"art_archived_mode\",\"match\":\"isEqual\",\"values\":\"1\",\"live\":\"\"}}]}', '', '', '', '', '_main_'),
(58, 874, 'content', 1, 'clear', '', '', '', '', '', '', '', '', '', '', '', 'clear', '', '', 0, '', 0, 1, '', '', '', '', '', '', '_main_');
